-- AlterTable
ALTER TABLE `booking` ADD COLUMN `referralSource` ENUM('SOCIAL_MEDIA', 'GOOGLE_SEARCH', 'FRIEND_REFERRAL', 'BUSINESS_REFERRAL', 'EXISTING_CUSTOMER', 'ONLINE_REVIEW', 'FORUM_COMMUNITY', 'OTHER') NULL,
    ADD COLUMN `referralSourceNotes` VARCHAR(500) NULL;
