-- AlterTable
ALTER TABLE `booking` MODIFY `status` ENUM('DRAFT', 'PENDING', 'IN_REVIEW', 'CONFIRMED', 'PENDING_DELIVERY', 'IN_QUEUE', 'IN_PROGRESS', 'RESOLVED', 'PENDING_PAYMENT', 'REJECTED', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'DELETED') NOT NULL DEFAULT 'DRAFT';
