-- AlterTable
ALTER TABLE `booking` MODIFY `status` ENUM('DRAFT', 'PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'CONTACTED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `booking_item` MODIFY `status` ENUM('DRAFT', 'IN_REVIEW', 'IN_QUEUE', 'IN_PROGRESS', 'COMPLETED', 'IN_RESOLUTION') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `system_role` MODIFY `isActive` BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE `user_role` MODIFY `isActive` BOOLEAN NOT NULL DEFAULT true;
